name: Deploy 
on: 
  push:
   branches:
    - main 
jobs:
  deploy:
    runs-on: self-hosted
    steps: 
      - name: Deploy to VM 
        shell: powershell 
        run: |
          cd C:\Users\sfx-admin\Downloads\MFA-Auth
          git pull origin main
          npm i
          redis-server
          npm run dev
